In [1]:
import os, h5py, glob
import numpy as np 
from astropy.table import Table, vstack

In [2]:
snapshot = 90
dat_dir = '/scratch/gpfs/chhahn/haloflow/groupcat/idark.ipmu.jp/hsc405/GroupCats/groups_0%i/' % snapshot

In [5]:
# compile subhalos and groups
tab_sub, tab_grp = [], []
for i in range(np.max([int(fsub.split('.')[-2]) for fsub in glob.glob(os.path.join(dat_dir, '*.hdf5'))])+1): 
    with h5py.File(os.path.join(dat_dir, 'fof_subhalo_tab_0%i.%i.hdf5' % (snapshot, i)), 'r') as fsub: 
        _tab = Table()
        for k in fsub['Subhalo'].keys():
            _tab[k] = fsub['Subhalo'][k][...]
        tab_sub.append(_tab)
    
    with h5py.File(os.path.join(dat_dir, 'fof_subhalo_tab_0%i.%i.hdf5' % (snapshot, i)), 'r') as fsub: 
        _tab = Table()
        for k in fsub['Group'].keys():
            _tab[k] = fsub['Group'][k][...]
        tab_grp.append(_tab)
        
tab_sub = vstack(tab_sub)        
tab_grp = vstack(tab_grp)   

In [6]:
tab_sub[:5]

<Table length=5>
SubhaloBHMass SubhaloBHMdot ... SubhaloVmaxRad SubhaloWindMass
   float32       float32    ...    float32         float32    
------------- ------------- ... -------------- ---------------
   0.57347244   0.000547174 ...    0.019830668     0.015698811
  0.053600773 6.4235473e-06 ...      1.1394057             0.0
  0.029704027 1.3411592e-05 ...      0.8740441    9.013242e-05
  0.020089064  6.082999e-06 ...      0.9455472             0.0
  0.019614158  4.138886e-06 ...      1.0609429             0.0

In [7]:
tab_grp[:5]

<Table length=5>
GroupBHMass GroupBHMdot  ... Group_R_Mean200 Group_R_TopHat200
  float32     float32    ...     float32          float32     
----------- ------------ ... --------------- -----------------
  0.9805005 0.0045273034 ...       1328.6283         1130.0176
  0.4214037  0.007083357 ...         991.668          842.1727
 0.37609854  0.004075157 ...       899.60345         770.36145
 0.27427444  0.015137708 ...        800.0801          677.6549
 0.23221496 0.0033231457 ...       642.45355          547.9594

In [11]:
tab_grp['GroupFirstSub'][1]

70033

In [12]:
tab_sub['SubhaloGrNr'][70033]

1

In [8]:
tab_grp['GroupFirstSub'][0]

5141735

In [6]:
tab_grp['Group_M_Crit200']

<MaskedColumn name='Group_M_Crit200' dtype='float32' length=10366762>
0.00067620893
          0.0
          0.0
          0.0
          0.0
          0.0
 0.0009528399
          0.0
          0.0
          0.0
          0.0
          0.0
          ...
          0.0
  0.004149464
          0.0
  0.003143717
 0.0039957804
 0.0037554929
          0.0
     63.13521
    47.938206
    62.213455
     71.56371
    66.258484

In [ ]:
pos_sub, pos_grp = [], [] 
subfind_id = [] 
for i in range(680): 
    _tab = h5py.File(os.path.join(dat_dir, 'fof_subhalo_tab_0%i.%i.hdf5' % (snapshot, i)))
    sub = _tab['Subhalo']
    if len(sub.keys()) > 0: 
        pos_sub.append(sub['SubhaloPos'][...])
    
    grp = _tab['Group']
    if len(grp.keys()) > 0: 
        mass = grp['Group_M_Crit200'][...]
        
        subfind_id.append(grp['GroupFirstSub'][...][mass > 0])
        pos_grp.append(grp['GroupPos'][...][mass > 0])
        
subfind_id = np.concatenate(subfind_id)
pos_sub = np.concatenate(pos_sub)
pos_grp = np.concatenate(pos_grp)

In [3]:
pos_sub, pos_grp = [], [] 
subfind_id = [] 
for i in range(680): 
    _tab = h5py.File(os.path.join(dat_dir, 'fof_subhalo_tab_0%i.%i.hdf5' % (snapshot, i)))
    sub = _tab['Subhalo']
    if len(sub.keys()) > 0: 
        pos_sub.append(sub['SubhaloPos'][...])
    
    grp = _tab['Group']
    if len(grp.keys()) > 0: 
        mass = grp['Group_M_Crit200'][...]
        
        subfind_id.append(grp['GroupFirstSub'][...][mass > 0])
        pos_grp.append(grp['GroupPos'][...][mass > 0])
        
subfind_id = np.concatenate(subfind_id)
pos_sub = np.concatenate(pos_sub)
pos_grp = np.concatenate(pos_grp)

In [12]:
_tab.keys()

<KeysViewHDF5 ['Config', 'Group', 'Header', 'IDs', 'Parameters', 'Subhalo']>

In [14]:
_tab['Subhalo'].keys()

<KeysViewHDF5 ['SubhaloBHMass', 'SubhaloBHMdot', 'SubhaloCM', 'SubhaloFlag', 'SubhaloGasMetalFractions', 'SubhaloGasMetalFractionsHalfRad', 'SubhaloGasMetalFractionsMaxRad', 'SubhaloGasMetalFractionsSfr', 'SubhaloGasMetalFractionsSfrWeighted', 'SubhaloGasMetallicity', 'SubhaloGasMetallicityHalfRad', 'SubhaloGasMetallicityMaxRad', 'SubhaloGasMetallicitySfr', 'SubhaloGasMetallicitySfrWeighted', 'SubhaloGrNr', 'SubhaloHalfmassRad', 'SubhaloHalfmassRadType', 'SubhaloIDMostbound', 'SubhaloLen', 'SubhaloLenType', 'SubhaloMass', 'SubhaloMassInHalfRad', 'SubhaloMassInHalfRadType', 'SubhaloMassInMaxRad', 'SubhaloMassInMaxRadType', 'SubhaloMassInRad', 'SubhaloMassInRadType', 'SubhaloMassType', 'SubhaloParent', 'SubhaloPos', 'SubhaloSFR', 'SubhaloSFRinHalfRad', 'SubhaloSFRinMaxRad', 'SubhaloSFRinRad', 'SubhaloSpin', 'SubhaloStarMetalFractions', 'SubhaloStarMetalFractionsHalfRad', 'SubhaloStarMetalFractionsMaxRad', 'SubhaloStarMetallicity', 'SubhaloStarMetallicityHalfRad', 'SubhaloStarMetallicityM

In [15]:
sub.keys()

<KeysViewHDF5 ['SubhaloBHMass', 'SubhaloBHMdot', 'SubhaloCM', 'SubhaloFlag', 'SubhaloGasMetalFractions', 'SubhaloGasMetalFractionsHalfRad', 'SubhaloGasMetalFractionsMaxRad', 'SubhaloGasMetalFractionsSfr', 'SubhaloGasMetalFractionsSfrWeighted', 'SubhaloGasMetallicity', 'SubhaloGasMetallicityHalfRad', 'SubhaloGasMetallicityMaxRad', 'SubhaloGasMetallicitySfr', 'SubhaloGasMetallicitySfrWeighted', 'SubhaloGrNr', 'SubhaloHalfmassRad', 'SubhaloHalfmassRadType', 'SubhaloIDMostbound', 'SubhaloLen', 'SubhaloLenType', 'SubhaloMass', 'SubhaloMassInHalfRad', 'SubhaloMassInHalfRadType', 'SubhaloMassInMaxRad', 'SubhaloMassInMaxRadType', 'SubhaloMassInRad', 'SubhaloMassInRadType', 'SubhaloMassType', 'SubhaloParent', 'SubhaloPos', 'SubhaloSFR', 'SubhaloSFRinHalfRad', 'SubhaloSFRinMaxRad', 'SubhaloSFRinRad', 'SubhaloSpin', 'SubhaloStarMetalFractions', 'SubhaloStarMetalFractionsHalfRad', 'SubhaloStarMetalFractionsMaxRad', 'SubhaloStarMetallicity', 'SubhaloStarMetallicityHalfRad', 'SubhaloStarMetallicityM

In [25]:
grp.keys()

<KeysViewHDF5 ['GroupBHMass', 'GroupBHMdot', 'GroupCM', 'GroupFirstSub', 'GroupGasMetalFractions', 'GroupGasMetallicity', 'GroupLen', 'GroupLenType', 'GroupMass', 'GroupMassType', 'GroupNsubs', 'GroupPos', 'GroupSFR', 'GroupStarMetalFractions', 'GroupStarMetallicity', 'GroupVel', 'GroupWindMass', 'Group_M_Crit200', 'Group_M_Crit500', 'Group_M_Mean200', 'Group_M_TopHat200', 'Group_R_Crit200', 'Group_R_Crit500', 'Group_R_Mean200', 'Group_R_TopHat200']>

In [23]:
sub['SubhaloGrNr'][...]

array([10299546, 10299551, 10299555, ..., 10366734, 10366735, 10366741],
      dtype=int32)

In [ ]:
sub['Subhalo']

In [10]:
_tab['Group'].keys()

<KeysViewHDF5 ['GroupBHMass', 'GroupBHMdot', 'GroupCM', 'GroupFirstSub', 'GroupGasMetalFractions', 'GroupGasMetallicity', 'GroupLen', 'GroupLenType', 'GroupMass', 'GroupMassType', 'GroupNsubs', 'GroupPos', 'GroupSFR', 'GroupStarMetalFractions', 'GroupStarMetallicity', 'GroupVel', 'GroupWindMass', 'Group_M_Crit200', 'Group_M_Crit500', 'Group_M_Mean200', 'Group_M_TopHat200', 'Group_R_Crit200', 'Group_R_Crit500', 'Group_R_Mean200', 'Group_R_TopHat200']>

In [4]:
subfind_id

array([      0,   70033,  100942, ..., 5806490, 5806491, 5806492],
      dtype=int32)

In [4]:
pos_sub[subfind_id] - pos_grp

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [5]:
np.save('/Users/chahah/data/frb_halos/centrals.subfind_id.npy', subfind_id)